### ISSUE TITLE
Formatting Logs

### ISSUE THREAD

**Issue by ThiccTony** [xdididon/WiFicon#1]
Hello,

After reviewing the code I noticed the usecols only support columns for ['BSSID', 'First time seen', 'Last time seen', 'channel', 'Speed', 'Privacy', 'Cipher', 'Authentication', 'ID-length' ,'ESSID'], would you be able to provide me the appropriate way to format the logs to make the script run?

Thanks!

**Comment by xdididon** [comment]
Hi,

Sorry for VERY late reply but I don’t have notifications on and hardly come here to check on things. I need to find the Bash script I used for this. If I remember well the issue was with spaces Airmon-ng adds to log files and some missing/junk data in the logs. I will add the file here when I find it.

Thanks,
